# coding: utf-8

# 牛丼
gyudon = Recipe.create(title: '家で本格の味!吉野家の牛丼を再現', comment: '有名チェーン店の牛丼の味を再現してみました!', amount: 4, calorie: 733, main_ingredient: '牛肉', category: 'ごはんもの', tips: '玉ねぎはくし切りに切る。<br>味付けは甘めが美味しいですね。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/gyudon/%E3%83%A1%E3%82%A4%E3%83%B3.jpeg', user_id: 1)
gyudon.ingredients.create([{index: 0, name: '水', amount: '100cc'}, {index: 1, name: '白ワイン', amount: '100cc'}, {index: 2, name: '砂糖', amount: '大さじ1'}, {index: 3, name: 'みりん', amount: '50cc'}, {index: 4, name: '昆布5cm角', amount: '1枚'}, {index: 5, name: 'ほんだし', amount: '小さじ1'}, {index: 6, name: '醤油', amount: '50cc'}, {index: 7, name: '牛バラ肉(オーストラリア産)', amount: '300g'}, {index: 8, name: '玉ねぎ中玉', amount: '2個'}, {index: 9, name: '紅生姜', amount: '適量'}, {index: 10, name: '卵', amount: '適量'}, ])
gyudon.procedures.create([{index: 0, description: '玉ねぎはくし切りに切る。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/gyudon/%E7%8E%89%E3%81%AD%E3%81%8D%E3%82%99%E3%82%92%E5%88%87%E3%82%8B.jpeg'}, {index: 1, description: 'だし汁材料を鍋に入れ沸騰させる。', image_url: ''}, {index: 2, description: '沸騰した昆布をとり出し、牛肉を入れる。', image_url: ''}, {index: 3, description: '牛肉の色が変わる(火がとおる)寸前に鍋から一旦全部出す。', image_url: ''}, {index: 4, description: '牛肉を出した鍋に玉ねぎを入れ、沸騰したら蓋をして弱火で20分待つ。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/gyudon/%E7%85%AE%E3%82%8B.jpeg'}, {index: 5, description: '牛肉を鍋に戻し、火を通す。', image_url: ''}, {index: 6, description: 'ご飯の上にかければ、牛丼の完成！', image_url: ''}, ])

# ツナときのこのトマトパスタ
tunaAndMushroomPasta = Recipe.create(title: 'ツナときのこのトマトパスタ', comment: 'ツナとキノコのきこり風トマトパスタ。ボスカイオーラともいいます。シンプル。包丁なしフライパンのみでおいしく作れます。', amount: 2, calorie: 713, main_ingredient: '果菜', category: 'パスタ', tips: 'コツはとくにありません。誰でも簡単においしくつくれると思います。材料欄には書きませんでしたが、アンチョビ、オレガノ、イタリアンパセリがあるとよりおいしくなります。今回、きのこはまいたけを使いましたが、しめじ、エリンギなどもおすすめです。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/tunaAndMushroomPasta/%E3%83%A1%E3%82%A4%E3%83%B3%E7%94%BB%E5%83%8F.jpeg', user_id: 1)
tunaAndMushroomPasta.ingredients.create([{index: 0, name: 'オリーブオイル', amount: '大さじ４'}, {index: 1, name: 'ニンニク（チューブ）', amount: '３〜４cm'}, {index: 2, name: 'きのこ（お好きなもの）', amount: 'ひとかぶ'}, {index: 3, name: 'ツナ缶（ノンオイル）', amount: '２缶'}, {index: 4, name: '白ワイン（なくても可）', amount: '８０cc'}, {index: 5, name: 'トマト缶', amount: '１缶'}, {index: 6, name: '塩', amount: '大さじ２'}, {index: 7, name: 'スパゲティ', amount: '一人８０gくらい'},  {index: 8, name: 'こしょう', amount: 'おこのみで'}, ])
tunaAndMushroomPasta.procedures.create([{index: 0, description: '最初にパスタ用のお湯を沸かし，フライパンにオリーブオイル、にんにくを入れ弱火で炒めます。今回は、アンチョビも入れました。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/tunaAndMushroomPasta/%E6%89%8B%E9%A0%861.jpeg'}, {index: 1, description: 'にんにくのいい香りがしてきたら、きのこを入れて中火で炒めます。今回はまいたけを使いました。ちょっと焦げ目がつくくらい。', image_url: ''}, {index: 2, description: 'ノンオイルのツナ缶を汁ごといれ、中火のまま少し炒めます。', image_url: ''}, {index: 3, description: '白ワインを入れて、中火で煮詰め、アルコールを飛ばします。', image_url: ''}, {index: 4, description: 'トマト缶を入れ、トマトをつぶして煮詰めます。火は少し弱めた方がいいかも。だいたい２０分くらい煮詰めるので→', image_url: ''}, {index: 5, description: '途中でスパゲティをゆで始めます。水１リットルあたり大さじ１の塩を入れます。', image_url: ''}, {index: 6, description: 'ソースを煮詰めるとこんな感じになります。オレガノを入れると２倍くらいおいしくなります。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/tunaAndMushroomPasta/%E6%89%8B%E9%A0%867.jpeg'}, {index: 7, description: 'フライパンにスパゲティを入れてあえます。お玉１～２杯のゆで汁を入れてください。', image_url: ''}, {index: 8, description: '塩こしょうで味を調え、盛り付けをして完成です。まいたけしゃきしゃきしておいしい。', image_url: ''}, ])

# 唐揚げ
karaage = Recipe.create(title: 'ザクザク食感が楽しい♡鶏の唐揚げ', comment: '下味をつけた鶏肉に衣をしっかりつけてザクザク食感が楽しめる鶏の唐揚げです♡', amount: 2, calorie: 415, main_ingredient: '鶏肉', category: '揚げ物', tips: '鶏を油に入れる際はしっかりボールにくっついている衣を箸などでくっつける(ザクザク食感)
よりザクザク感をupしたい場合は水と片栗粉の量を大さじ1ほど微調整して衣を多めにしてください♡お好みで♪', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/karaage/%E3%83%A1%E3%82%A4%E3%83%B3%E7%94%BB%E5%83%8F.jpeg', user_id: 1)
karaage.ingredients.create([{index: 0, name: '鶏モモ肉', amount: '１枚'}, {index: 1, name: 'お酒', amount: '大さじ１'}, {index: 2, name: '醤油', amount: '大さじ１'}, {index: 3, name: '水', amount: '大さじ１'}, {index: 4, name: 'ニンニクすりおろし', amount: '小さじ２'}, {index: 5, name: 'ショウガ', amount: '小さじ２'}, {index: 6, name: '片栗粉', amount: '大さじ５'}, {index: 7, name: 'すりごま', amount: '大さじ１'}, {index: 8, name: '油', amount: '鍋に合わせて鶏肉が浸かるくらい'}, ])
karaage.procedures.create([{index: 0, description: '鶏モモ肉を８等分に切る
ボールに入れ、お酒、醤油、水、ニンニクすりおろし、ショウガすりおろしを入れる', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/karaage/%E6%89%8B%E9%A0%861.jpeg'}, {index: 1, description: 'しっかり混ぜ込み、ラップをして１時間冷蔵庫で寝かせる', image_url: ''}, {index: 2, description: '片栗粉、すり胡麻(お好みで)を入れて混ぜる', image_url: ''}, {index: 3, description: '水気が無くなり、鶏同士がくっつくくらいが目安', image_url: ''}, {index: 4, description: '180℃の油で約5～６分揚げる<br>鶏にボールにくっついている衣をしっかりつけながら油に入れていく<br>途中ひっくり返す', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/karaage/%E6%89%8B%E9%A0%865.jpeg'}, {index: 5, description: 'キレイな色に揚がれば出来上がり♪', image_url: ''}, ])

# ハンバーグ
hamburgSteak = Recipe.create(title: '簡単！煮込みハンバーグ', comment: 'トマトケチャップ＋とんかつソースで簡単にデミグラス風に！', amount: 4, calorie: 304, main_ingredient: 'ひき肉', category: '肉料理', tips: 'ハンバーグは煮込むことでしっかり火が通り、ふっくらと仕上がります。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/hamburg/%E3%83%A1%E3%82%A4%E3%83%B3%E7%94%BB%E5%83%8F.jpg', user_id: 1)
hamburgSteak.ingredients.create([{index: 0, name: '○ 合挽肉', amount: '300g'}, {index: 1, name: '○ 玉ねぎ', amount: '中1/2個'}, {index: 2, name: '○ パン粉', amount: '1/3カップ'}, {index: 3, name: '○ 牛乳', amount: '大さじ2'}, {index: 4, name: '○ 溶き卵', amount: '1個分'}, {index: 5, name: '○ 塩', amount: '少々'}, {index: 6, name: '○ こしょう', amount: '少々'}, {index: 7, name: '○ サラダ油', amount: '小さじ1/2'}, {index: 8, name: '※ ブロッコリー', amount: '1/3株'}, {index: 9, name: '※ しめじ', amount: '1/2パック'}, {index: 10, name: '※ 赤パプリカ', amount: '1/2個'}, {index: 11, name: 'ケチャップ', amount: '大さじ6'}, {index: 12, name: 'とんかつソース', amount: '大さじ3'}, {index: 13, name: '水', amount: '150cc'}, ])
hamburgSteak.procedures.create([{index: 0, description: '※のブロッコリー、しめじは小房に分け、赤パプリカは2cm幅に切る。', image_url: ''}, {index: 1, description: 'ボウルにサラダ油以外の○の材料を入れてこね、4等分にし小判型にととのえる。', image_url: ''}, {index: 2, description: 'フライパンにサラダ油を熱し、(2)を入れ両面に焼き色をつける。', image_url: ''}, {index: 3, description: '(1)を加え、焼き色がついたらデミグラス風煮込みソースの材料を加える。', image_url: ''}, {index: 4, description: '沸騰したら火を弱め、フタをして煮込む。', image_url: ''}, ])

# 野菜炒め
yasaiitame = Recipe.create(title: '簡単おいしい！肉野菜炒め', comment: '簡単でおいしい、定番の肉野菜炒めのご紹介です。強火でさっと炒めたシャキシャキの野菜とジューシーな豚肉に、オイスターソースのコクが効いた味付けがよく合います。お好みのお肉や野菜を使ってアレンジもできるので、ぜひお試しくださいね。', amount: 2, calorie: 150, main_ingredient: '葉物野菜', category: '炒め物', tips: '豚こま切れ肉は、お好みの部位や形状のものに代えてもお作りいただけます。
調味料の加減は、お好みで調整してください。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/yasaiitame/%E3%83%A1%E3%82%A4%E3%83%B3%E7%94%BB%E5%83%8F.jpg', user_id: 1)
yasaiitame.ingredients.create([{index: 0, name: '豚こま切れ肉', amount: '150g'}, {index: 1, name: '薄力粉', amount: '小さじ1'}, {index: 2, name: '塩こしょう', amount: 'ひとつまみ'}, {index: 3, name: 'にんじん', amount: '1/3本'}, {index: 4, name: 'キャベツ', amount: '200g'}, {index: 5, name: 'もやし', amount: '100g'}, {index: 6, name: 'ピーマン', amount: '2個'}, {index: 7, name: '(A)料理酒', amount: '大さじ1'}, {index: 8, name: '(A)しょうゆ', amount: '大さじ1/2'}, {index: 9, name: '(A)オイスターソース', amount: '大さじ1/2'}, {index: 10, name: '(A)鶏ガラスープの素', amount: '小さじ1'}, {index: 11, name: 'サラダ油', amount: '大さじ1/2'}, ])
yasaiitame.procedures.create([{index: 0, description: 'にんじんは皮をむきます。ピーマンはヘタと種を取り除いておきます。', image_url: ''}, {index: 1, description: 'にんじんは短冊切りにします。', image_url: ''}, {index: 2, description: 'キャベツは一口大に切ります。ピーマンは1cm幅に切ります。', image_url: ''}, {index: 3, description: 'ボウルに(A)を入れて混ぜ合わせます。', image_url: ''}, {index: 4, description: '豚こま切れ肉に薄力粉をまぶします。', image_url: ''}, {index: 5, description: '
中火で熱したフライパンにサラダ油をひき、4を入れて炒めます。色が変ったら塩こしょうをふり、さっと炒めて一度取り出します。', image_url: ''}, {index: 6, description: '
同じフライパンを強火で熱し、1を入れて炒めます。', image_url: ''}, {index: 7, description: 'にんじんに火が通ったら2ともやしを入れて強火で炒めます。', image_url: ''}, {index: 8, description: 'キャベツがしんなりしたら5と3を入れて強火のまま炒めます。', image_url: ''}, {index: 9, description: '全体に味がなじんだら火から下ろし、器に盛り付けて完成です。', image_url: ''}, ])

# 筑前煮
chikuzenni = Recipe.create(title: '基本の筑前煮', comment: '筑前煮は、さまざまな具材の旨み・風味が出るので、特にだし汁は必要ありません（干し椎茸の戻し汁だけ使います）。<br>はじめに具材を炒める・最後は少し煮詰めるのがポイント。日持ちもするので、ぜひたっぷり作ってみてください。', amount: 6, calorie: 109, main_ingredient: '根菜', category: '煮物', tips: '今回、筑前煮はたっぷりの量で作ったほうが美味しくなるので、少し多めのレシピになっています。日持ちも冷蔵庫で5日ほど（目安として）するものなので、ぜひ多めの分量で作ってみてください。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/chikuzenni/%E3%83%A1%E3%82%A4%E3%83%B3%E7%94%BB%E5%83%8F.jpeg', user_id: 1)
chikuzenni.ingredients.create([{index: 0, name: '鶏もも肉', amount: '1枚（300ｇほど）'}, {index: 1, name: '干し椎茸', amount: '4〜5枚'}, {index: 2, name: 'こんにゃく', amount: '１枚'}, {index: 3, name: 'れんこん', amount: '300ｇ'}, {index: 4, name: 'ごぼう', amount: '2/3本（100ｇほど）'}, {index: 5, name: 'にんじん', amount: '1/2本'}, {index: 6, name: '里芋', amount: '400ｇ（中サイズで5〜6個）'}, {index: 7, name: '絹さや', amount: '6〜7枚'}, {index: 8, name: 'サラダ油,米油,菜種油などの植物油', amount: '小さじ１'}, {index: 9, name: '椎茸の戻し汁', amount: '150ml使用'}, {index: 10, name: '醤油', amount: '大さじ5'}, {index: 11, name: '酒', amount: '大さじ４'}, {index: 12, name: 'みりん', amount: '大さじ４'}, ])
chikuzenni.procedures.create([{index: 0, description: 'はじめに、干し椎茸はさっと洗ってからひたひたの水に数時間浸けておきます。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/chikuzenni/%E6%A4%8E%E8%8C%B8%E4%B8%8B%E3%81%93%E3%82%99%E3%81%97%E3%82%89%E3%81%88.jpeg'}, {index: 1, description: 'れんこんとごぼうは皮をむいて、食べやすい大きさの乱切りにします（ごぼうは大きめのひと口大、れんこんはそれよりも大きくてOKです）。それぞれ水にさらします。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/chikuzenni/%E3%83%AC%E3%83%B3%E3%82%B3%E3%83%B3%E3%82%B3%E3%82%99%E3%83%9B%E3%82%99%E3%82%A6%E4%B8%8B%E3%81%93%E3%82%99%E3%81%97%E3%82%89%E3%81%88.jpeg'}, {index: 2, description: 'にんじんは小さめの乱切りにして、椎茸は軸を除いて2〜3等分に切ります。椎茸の戻し汁はごみがあれば茶こしなどで除き、150mlはかっておきます。', image_url: ''}, {index: 3, description: '里芋は皮をむいて大きければ2〜3等分に切ります。里芋だけは火が通りづらいので事前に下ゆでしておきます（水から火にかけ、沸いたら3〜4分ゆでてざる上げします）。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/chikuzenni/%E9%87%8C%E8%8A%8B%E4%B8%8B%E3%81%93%E3%82%99%E3%81%97%E3%82%89%E3%81%88.jpeg'}, {index: 4, description: 'こんにゃくはスプーンでちぎり、塩もみしてから2〜3分ゆでてざる上げします。', image_url: ''}, {index: 5, description: '鶏肉は余分な脂や皮があれば切り落とし、皮を下にして3〜4㎝四方に切ります。これで具材の下ごしらえの完了です。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/chikuzenni/%E5%85%A8%E3%81%A6%E3%81%AE%E6%9D%90%E6%96%99.jpeg'}, {index: 6, description: '大きめの鍋やフライパンに油小さじ1を入れて弱めの中火にかけます。', image_url: ''}, {index: 7, description: '鶏肉、水気を切ったれんこん、ごぼう、にんじん、こんにゃくを加えて炒め合わせます。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/chikuzenni/%E7%82%92%E3%82%81%E3%82%8B.jpeg'}, {index: 8, description: '鶏肉や根菜類を炒め合わせることで、油に香りが移ってより美味しくなります。全体に油がまわって、野菜の表面に少し透明感が出てくるまで炒めましょう。', image_url: ''}, {index: 9, description: '里芋と干し椎茸を加えます。続けて椎茸の戻し汁150mlと調味料（醤油大さじ5、酒とみりん各大さじ4）を加えてから混ぜ合わせます。', image_url: ''}, {index: 10, description: '落し蓋をして煮ていきます。煮るときの火加減は弱めの中火、煮る時間は【10分】です。', image_url: ''}, {index: 11, description: '鍋肌ではぐつぐつと煮汁が沸くのが見え、落し蓋の下の煮汁もしっかり煮汁が対流する沸き具合を保つことが大切です。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/chikuzenni/%E7%85%AE%E3%82%8B.jpeg'}, {index: 12, description: '完全に煮汁を飛ばすと味が濃くなるので、時おり具材全体を混ぜながら煮詰め、煮汁が少なくなって鍋底一面に煮汁が残るくらいになれば一度味見をして確認してみましょう。', image_url: ''}, {index: 13, description: '煮詰め加減が味の濃さにもつながるので、好みの加減になれば火を止め、食べる時に塩ゆでした絹さやを散らすなどすると色合いもきれいに仕上がります。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/chikuzenni/%E5%AE%8C%E6%88%90%E9%96%93%E8%BF%91.jpeg'}, ])

# かぼちゃの煮物
kabocha = Recipe.create(title: 'レンジで簡単☆かぼちゃの煮物', comment: 'レンジで出来るので簡単です。水分を使わないのでホクホクかぼちゃの煮物です。', amount: 3, calorie: 128, main_ingredient: '果菜', category: '煮物', tips: 'コンロを使わず火加減も気にしなくていいので簡単です。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/kabocha/%E3%83%A1%E3%82%A4%E3%83%B3%E7%94%BB%E5%83%8F.jpeg', user_id: 1)
kabocha.ingredients.create([{index: 0, name: 'かぼちゃ', amount: 'かぼちゃ1/4個(400gくらい)'}, {index: 1, name: '砂糖', amount: '大さじ1'}, {index: 2, name: 'しょうゆ', amount: '大さじ1/2'}, ])
kabocha.procedures.create([{index: 0, description: 'かぼちゃは食べやすい大きさに切る。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/kabocha/%E6%89%8B%E9%A0%861.jpeg'}, {index: 1, description: '耐熱のお皿にならべる。ラップをして600W5分半加熱する。', image_url: ''}, {index: 2, description: '竹串をさしてスーッとささればokです。砂糖としょうゆをかけてもう一度ラップをして1分加熱。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/kabocha/%E6%89%8B%E9%A0%863.jpeg'}, {index: 3, description: '出来上がり♪', image_url: ''}, ])

# きのこのガーリックチーズトースト
kinokoGarlic = Recipe.create(title: 'きのこのガーリックチーズトースト', comment: '意外と手間がかかるガーリックトーストを、フライパンを使って手軽に楽しむことができるレシピです。きのこをたっぷり使った食べ応えのあるひと皿は、急なお客様へのおもてなしにもぴったり。', amount: 4, calorie: 193, main_ingredient: 'きのこ', category: 'パン', tips: '・トマトやナスなどの野菜をたっぷり加えてパングラタンにしても◎。<br>・食べきれなかったバケットやフランスパンを使って、気軽につくれるレシピです。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/kinokoGarlic/%E3%83%A1%E3%82%A4%E3%83%B3%E7%94%BB%E5%83%8F.jpg', user_id: 1)
kinokoGarlic.ingredients.create([{index: 0, name: '舞茸', amount: '100g'}, {index: 1, name: 'しめじ', amount: '100g'}, {index: 2, name: 'バケット', amount: '80g（15cmくらい）'}, {index: 3, name: 'にんにく', amount: '1かけ（5g）'}, {index: 4, name: 'オリーブオイル', amount: '大さじ2'}, {index: 5, name: 'バター', amount: '20g'}, {index: 6, name: 'ミックスチーズ', amount: '30g'}, {index: 7, name: '大葉', amount: '3枚'}, {index: 8, name: '塩、黒こしょう', amount: '各適量'}, ])
kinokoGarlic.procedures.create([{index: 0, description: '	きのこ類は石づきをとり、ほぐしておく。バケットは2cm角、にんにくはみじん切りにする。', image_url: ''}, {index: 1, description: '	フライパンに、にんにく、オリーブオイル、バターを入れて弱火で火にかけ、香りが出たら中火でバケットを入れて2～3分こんがりと焼く。きのこを加えて炒め、塩こしょうで味付けをする。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/kinokoGarlic/%E6%89%8B%E9%A0%862.jpg'}, {index: 2, description: '器に入れ、チーズをかけてオーブントースターで3～5分焼く。 細かく切った大葉をふる。', image_url: ''}, ])

# サーモンとほうれんそうのクリーム煮
salmon = Recipe.create(title: 'サーモンとほうれんそうのクリーム煮', comment: '寒い日に嬉しいホットメニュー', amount: 2, calorie: 289, main_ingredient: '鮭', category: 'スープ・汁物・シチュー', tips: '', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/salmon/%E3%83%A1%E3%82%A4%E3%83%B3%E7%94%BB%E5%83%8F.jpg', user_id: 1)
salmon.ingredients.create([{index: 0, name: 'サーモン切身', amount: '２切れ'}, {index: 1, name: 'ほうれんそう', amount: '１／２束（１００ｇ）'}, {index: 2, name: '玉ねぎ', amount: '１／２個'}, {index: 3, name: 'しめじ', amount: '１袋'}, {index: 4, name: '牛乳', amount: '１カップ'}, {index: 5, name: '塩、こしょう、小麦粉', amount: '各適量'}, {index: 6, name: 'サラダ油', amount: '適量'}, {index: 7, name: '(a)顆粒コンソメ', amount: '小さじ１と１／２'}, {index: 8, name: '(a)湯', amount: '１カップ'}, ])
salmon.procedures.create([{index: 0, description: 'ほうれんそうは根元を切って洗い、耐熱容器にのせ、ラップをふんわりとかけて６００Ｗの電子レンジで３分加熱する。冷水にとって水気を絞り、５ｃｍ幅に切る。玉ねぎは薄切り、しめじは石づきを除いてほぐす。', image_url: ''}, {index: 1, description: 'サーモンは大きめのひと口大に切り、塩、こしょうをふり、小麦粉をまぶす。（ａ）を混ぜ合わせておく。', image_url: ''}, {index: 2, description: 'フライパンに油を熱し、サーモンの両面をこんがり焼いて取り出す。同じフライパンに玉ねぎを加えて炒め、小麦粉大さじ２をふり入れ、弱火で約３分炒める。', image_url: ''}, {index: 3, description: '3に（ａ）を加えて伸ばし、しめじ、牛乳を加えて１０分煮る。とろみがついたらほうれんそうとサーモンを加えて塩、こしょうで味をととのえる。', image_url: ''}, ])

# 王道のさばのみそ煮
sabamisoni = Recipe.create(title: '王道のさばのみそ煮', comment: '王道・基本のさばのみそ煮の作り方です。ぜひお試しください。', amount: 4, calorie: 285, main_ingredient: 'サバ', category: '魚介料理', tips: 'さばに塩少々を振って冷蔵庫で20～30分おくことで、魚の臭みがとれ、ほどよく身がしまり、魚料理が格段に美味しくなります。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/saba/%E3%83%A1%E3%82%A4%E3%83%B3%E7%94%BB%E5%83%8F.jpg', user_id: 1)
sabamisoni.ingredients.create([{index: 0, name: 'さば', amount: '1尾分(2枚おろし)'}, {index: 1, name: 'しょうが', amount: '1/2片'}, {index: 2, name: '味噌', amount: '大さじ4'}, {index: 3, name: '酒', amount: '大さじ4'}, {index: 4, name: '塩', amount: '少々'}, {index: 5, name: 'しょうゆ', amount: '大さじ1'}, {index: 6, name: '水', amount: '150cc'}, {index: 7, name: 'みりん', amount: '大さじ4'}, ])
sabamisoni.procedures.create([{index: 0, description: 'さばは4等分にし、塩少々を振って冷蔵庫で20～30分おく。出てきた水分をペーパータオルで丁寧にふきとる。
しょうがは薄切りにしておく。', image_url: ''}, {index: 1, description: 'フライパンまたは平鍋に酒とみりんを強火で煮立て、アルコール分が飛んだら分量の水、しょうゆを加える。', image_url: ''}, {index: 2, description: '再び煮立ったらさばを重ならないよう皮目を上にして並べ入れ、しょうがを散らし、落としぶたをして中火で3～4分煮る。', image_url: ''}, {index: 3, description: '落としぶたをはずし、「料亭の味(だし入り)」を[3]の煮汁適量でのばして[3]に加えてなじませ、さばに煮汁をかけながらさらに3～4分煮る。', image_url: ''}, {index: 4, description: 'さばを鍋から取り出して器に盛り付ける。残った煮汁はとろりとするまで煮詰め、さばの上にかける。', image_url: ''}, ])

# ぶり大根
buridaikon = Recipe.create(title: 'ぶり大根', comment: 'ぶりのうまみが大根にもじっくりしみた定番の煮もの。しっかりと甘みをきかせた、昔ながらの味わいです。', amount: 4, calorie: 293, main_ingredient: 'ブリ', category: '煮物', tips: '', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/buridaikon/%E3%83%A1%E3%82%A4%E3%83%B3%E7%94%BB%E5%83%8F.jpg', user_id: 1)
buridaikon.ingredients.create([{index: 0, name: 'ぶりの切り身', amount: '3切れ'}, {index: 1, name: '大根', amount: '2/3本（約600g）'}, {index: 2, name: '酒', amount: '適量'}, {index: 3, name: '砂糖', amount: '適量'}, {index: 4, name: 'しょうゆ', amount: '適量'}, {index: 5, name: 'みりん', amount: '適量'}, ])
buridaikon.procedures.create([{index: 0, description: 'ぶりは一切れを3等分にする。大根は厚さ2cmの輪切りにし、やや厚めに皮をむいて、半分に切る。', image_url: ''}, {index: 1, description: 'ボールに氷水を用意しておく。鍋にたっぷりの湯を沸かし、酒少々を入れる。ぶりを加えて、表面が白くなる程度に、さっと湯通しし、すぐに氷水にとる。', image_url: ''}, {index: 2, description: '鍋をざっと洗い、大根とかぶるくらいの水を入れる。中火にかけ、大根に竹串がすーっと通るまでゆでる', image_url: ''}, {index: 3, description: 'ぶりを戻し入れ、酒大さじ5、砂糖大さじ4を入れる。落としぶたをして弱火で、7分くらい煮る。', image_url: ''}, {index: 4, description: 'しょうゆ大さじ3、みりん大さじ1を加え、煮汁が少し残る程度まで、さらに3分くらい煮つめる。', image_url: ''}, ])

# 海老とブロッコリーのマカロニグラタン
ebiguratan = Recipe.create(title: '海老とブロッコリーのマカロニグラタン', comment: '王道のグラタンです！', amount: 2, calorie: 430, main_ingredient: 'えび', category: 'グラタン・ドリア・ラザニア', tips: '牛乳の半量を生クリームに変えると、抜群にコクが出ます。<br>ベーコン、ツナ缶、コーン缶、シーフードミックス、鶏肉、ほうれん草など、アレンジ無限大です。お好みの食材で作ってみてください。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/ebiguratan/%E3%83%A1%E3%82%A4%E3%83%B3%E7%94%BB%E5%83%8F.jpeg', user_id: 1)
ebiguratan.ingredients.create([{index: 0, name: 'マカロニ', amount: '70g'}, {index: 1, name: 'ブロッコリー(小房)', amount: '4個'}, {index: 2, name: 'バター', amount: '20g'}, {index: 3, name: '玉ねぎ(スライス)', amount: '1/4個'}, {index: 4, name: 'マッシュルーム(スライス)', amount: '4個'}, {index: 5, name: 'むき海老(背ワタを取る)', amount: '10尾'}, {index: 6, name: 'パプリカ(赤)', amount: '1/6個'}, {index: 7, name: '薄力粉', amount: '大さじ2'}, {index: 8, name: '牛乳', amount: '250cc'}, {index: 9, name: '顆粒コンソメ', amount: '小さじ1'}, {index: 10, name: '塩', amount: '少々'}, {index: 11, name: 'ホワイトペッパー', amount: '少々'}, {index: 12, name: 'ピザ用チーズ', amount: '大さじ4'}, ])
ebiguratan.procedures.create([{index: 0, description: '鍋にお湯を沸かし、マカロニを袋の表示より1分短く茹でる。マカロニと一緒にブロッコリーも入れて茹で、お湯を切る。', image_url: ''}, {index: 1, description: 'フライパンにバターを熱し、玉ねぎを入れて炒める。玉ねぎが透き通ったらマッシュルームとむき海老とパプリカを加えて炒める。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/ebiguratan/%E7%8E%89%E3%81%AD%E3%81%8D%E3%82%99%E3%81%88%E3%81%B2%E3%82%99%E3%82%92%E7%82%92%E3%82%81%E3%82%8B.jpeg'}, {index: 2, description: '薄力粉をふり入れ、粉っぽさがなくなるまで炒める。牛乳を少しずつ加えてのばし、顆粒コンソメ、塩、ホワイトペッパーを加える。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/ebiguratan/%E7%89%9B%E4%B9%B3%E3%82%92%E5%8A%A0%E3%81%88%E3%82%8B.jpeg'}, {index: 3, description: 'とろみがついたら塩火から下ろし、バター(分量外)を側面に塗った耐熱皿に入れる。', image_url: ''}, {index: 4, description: 'ピザ用チーズをのせ、トースターでこんがり焼き色がつくまで7〜8分焼いて出来上がり。', image_url: ''}, ])

# あっさりと☆牡蠣の白菜鍋
kakiNabe = Recipe.create(title: 'あっさりと☆牡蠣の白菜鍋', comment: '寄せ鍋風にあっさりと‼️', amount: 2, calorie: 280, main_ingredient: '貝類', category: '鍋料理', tips: '牡蠣はに煮過ぎると硬くなります。<br>締めはうどんが美味です！', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/kakinabe/%E3%83%A1%E3%82%A4%E3%83%B3%E7%94%BB%E5%83%8F.jpg', user_id: 1)
kakiNabe.ingredients.create([{index: 0, name: '生牡蠣', amount: '100g'}, {index: 1, name: '白菜', amount: '3枚'}, {index: 2, name: 'えのき', amount: '1束'}, {index: 3, name: '豆腐', amount: '1丁'}, {index: 4, name: '○だし汁', amount: '3カップ'}, {index: 5, name: '○醤油、酒、みりん', amount: '各大さじ1.5〜'}, ])
kakiNabe.procedures.create([{index: 0, description: '生牡蠣は下処理すべきものは塩水に入れ洗い流し、水気を切ります。<br>白菜は食べやすく切り、えのきは石づきを切り取りほぐします。<br>豆腐は食べやすく切ります。', image_url: ''}, {index: 1, description: '鍋に○を入れ火にかけ、白菜、えのき、豆腐を入れます。<br>白菜がしんなりしたら、牡蠣を入れ一煮立ちして牡蠣がぷっくりし、火が入ると、出来上がり。', image_url: ''}, ])

# 豆腐入りフワフワお好み焼き
tofuOkonomiyaki = Recipe.create(title: '豆腐入りフワフワお好み焼き', comment: '絹ごし豆腐入りのフワフワなお好み焼きのご紹介です。とろけるチーズのコクとあげ玉のさくさくの食感がおいしくてついついお箸が止まりませんよ。ビールにもよく合いますのでちょっとしたおもてなしにも喜ばれます。お手軽な材料でできますので今晩のおかずにぜひ、お試しくださいね。', amount: 2, calorie: 578, main_ingredient: '豆腐', category: '粉物', tips: '絹ごし豆腐は木綿豆腐でも代用できます。<br>トッピングの材料はお好みで調整してください。<br>ピザ用チーズはお好みのチーズで代用できます。<br>最後に裏返して強火で焼くことでパリッとおいしく仕上がります。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/tofuOkonomiyaki/%E3%83%A1%E3%82%A4%E3%83%B3%E7%94%BB%E5%83%8F.jpg', user_id: 1)
tofuOkonomiyaki.ingredients.create([{index: 0, name: '<具材>キャベツ', amount: '200g'}, {index: 1, name: '<具材>ピザ用チーズ', amount: '50g'}, {index: 2, name: '<具材>あげ玉', amount: '20g'}, {index: 3, name: '<具材>釜揚げしらす', amount: '25g'}, {index: 4, name: '<生地>絹ごし豆腐', amount: '150g'}, {index: 5, name: '<生地>卵', amount: '2個'}, {index: 6, name: '<生地>薄力粉', amount: '大さじ4'}, {index: 7, name: '<生地>マヨネーズ', amount: '大さじ1'}, {index: 8, name: '<生地>ベーキングパウダー', amount: '小さじ1/2'}, {index: 9, name: 'ごま油', amount: '大さじ2'}, {index: 10, name: '<トッピング>お好み焼きソース', amount: '大さじ2'}, {index: 11, name: '<トッピング>マヨネーズ', amount: '大さじ2'}, {index: 12, name: '<トッピング>かつお節', amount: '2g'}, {index: 13, name: '<トッピング>青のり', amount: '適量'}, ])
tofuOkonomiyaki.procedures.create([{index: 0, description: 'キャベツは粗みじん切りにします。', image_url: ''}, {index: 1, description: 'ボウルに生地の材料を入れてホイッパーで混ぜ合わせ、1、残りの具材の材料を入れてよく混ぜ合わせます。', image_url: ''}, {index: 2, description: 'フライパンに半量のごま油を入れて中火にし、2の半量を入れて焼きます。', image_url: ''}, {index: 3, description: '焼き色がついたら裏返し蓋をして5分程焼きます。', image_url: ''}, {index: 4, description: '焼き色がつき、中まで火が通ったら表に返して強火にし、1分程焼いたら火から下ろします。同様にもう1枚焼きます。', image_url: ''}, {index: 5, description: '食べやすい大きさに切り、器に盛り付けてお好み焼きソース、マヨネーズ、かつお節、青のりをかけて出来上がりです。', image_url: ''}, ])

# 本格餃子
gyoza = Recipe.create(title: '本格餃子', comment: 'シャキシャキ野菜をたっぷり混ぜ混みしっかりと下味を付けました！', amount: 2, calorie: 480, main_ingredient: 'ひき肉', category: '餃子・焼売・春巻き', tips: '10の盛り付け方は水分や油が残っていると火傷の原因になり危ないので注意して下さい。<br>不慣れな場合は無理をせずフライ返し等で取って盛り付けて下さい。<br>26㎝のフライパン(必ずくっつかないフライパンを使う)にぎっしり並べると一度で焼けます。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/gyoza/%E3%83%A1%E3%82%A4%E3%83%B3%E7%94%BB%E5%83%8F.jpeg', user_id: 1)
gyoza.ingredients.create([{index: 0, name: '餃子の皮(普通のサイズ)', amount: '25～30枚位'}, {index: 1, name: '豚ひき肉', amount: '200g'}, {index: 2, name: 'キャベツ', amount: '200g'}, {index: 3, name: '青ネギ(白ネギでも可)', amount: '50g(1/2本)'}, {index: 4, name: 'にら', amount: '50g(1/2本)'}, {index: 5, name: '☆鶏ガラスープの素(顆粒)', amount: '2g(小1/2)'}, {index: 6, name: '☆酒', amount: '5g(小1)'}, {index: 7, name: '☆みりん', amount: '6g(小1)'}, {index: 8, name: '☆濃口醤油', amount: '6g(小1)'}, {index: 9, name: '☆おろしにんにく', amount: '5g(小1)'}, {index: 10, name: '☆おろししょうが', amount: '3g(小1弱)'}, {index: 11, name: '☆ごま油', amount: '4g(小1)'}, {index: 12, name: '塩(野菜の塩揉み用)', amount: '5g'}, {index: 13, name: '塩', amount: '少々'}, {index: 14, name: 'こしょう', amount: '少々'}, {index: 15, name: 'ごま油(焼く時)', amount: '15g(大1強)'}, {index: 16, name: '<タレ>濃口醤油', amount: '大1(18g)'}, {index: 17, name: '<タレ>薄口醤油', amount: '大1(18g)'}, {index: 18, name: '<タレ>砂糖', amount: '大1(9g)'}, {index: 19, name: '<タレ>酢', amount: '大2/3(10g)'}, {index: 20, name: '<タレ>ラー油(お好みで)', amount: '適量'}, ])
gyoza.procedures.create([{index: 0, description: 'キャベツ、ニラ、青ネギをそれぞれ小さく切る。塩をかけて全体に混ぜ野菜がしんなりするまでしばらくおく。', image_url: ''}, {index: 1, description: '☆を混ぜ合わせておく。(餃子の下味用)', image_url: ''}, {index: 2, description: 'タレの材料は混ぜ合わせておく。', image_url: ''}, {index: 3, description: 'ひき肉に塩こしょう、2の調味料を加えてしっかり混ぜる。', image_url: ''}, {index: 4, description: '1の野菜がしんなりしたら手で水分を絞ってひき肉と混ぜ合わせる。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/gyoza/%E6%89%8B%E9%A0%865.jpeg'}, {index: 5, description: '餃子の皮に具を乗せ、縁に水を付け、ひだをつけながら包む。
(具が多すぎると包みにくくなるのでで加減して下さい)', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/gyoza/%E6%89%8B%E9%A0%866.jpeg'}, {index: 6, description: '包んだ餃子はキッチンペーパーを敷いたお皿の上に並べる。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/gyoza/%E6%89%8B%E9%A0%867.jpeg'}, {index: 7, description: 'ごま油を全体に塗ったフライパン(26㎝)に餃子を綺麗に並べて火を付ける。強火で軽く焼き色が付くまで焼く。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/gyoza/%E6%89%8B%E9%A0%868.jpeg'}, {index: 8, description: '水100ccを全体に回しかけ、すぐに蓋をし中火で5分焼く。
(片手に水、片手に蓋を持ってすぐに蓋をする！！)', image_url: ''}, {index: 9, description: '蓋を外して水分が完全に無くなり、焼き色をつけた面がカラッとするまで焼く。
水分が無くなると焦げやすくなるので注意する！', image_url: ''}, {index: 10, description: 'フライパンを揺すって餃子がくっついていない事を確認し、サイズの合うお皿を乗せてしっかり押さえながら裏返して盛り付ける。', image_url: ''}, ])

# 豚の生姜焼き
shogayaki = Recipe.create(title: 'ご飯が進む！豚肉の生姜焼き', comment: '今晩のおかずに、ごはんとの相性抜群の豚の生姜焼きはいかがでしょうか。さわやかな生姜の香りのたれがしっかり絡んだ肉は、ごはんのおかずだけでなく、お酒のおつまみにもピッタリです。キャベツをたっぷり添えてお召し上がりくださいね。', amount: 2, calorie: 374, main_ingredient: '豚肉', category: '肉料理', tips: 'ごま油は、サラダ油でも代用いただけます。<br>豚ロースは、お好みの部位に代えてもお作りいただけます。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/shogayaki/%E3%83%A1%E3%82%A4%E3%83%B3%E7%94%BB%E5%83%8F.jpg', user_id: 1)
shogayaki.ingredients.create([{index: 0, name: '豚ロース(薄切り)', amount: '300g'}, {index: 1, name: '薄力粉', amount: '大さじ1'}, {index: 2, name: '<たれ>すりおろし生姜', amount: '<たれ>大さじ2'}, {index: 3, name: '<たれ>しょうゆ', amount: '大さじ2'}, {index: 4, name: '<たれ>砂糖', amount: '大さじ1'}, {index: 5, name: '料理酒', amount: '大さじ1'}, {index: 6, name: 'ごま油', amount: '大さじ1'}, {index: 7, name: '<付け合わせ>キャベツ', amount: '150g'}, {index: 8, name: '<付け合わせ>トマト', amount: '1個'}, ])
shogayaki.procedures.create([{index: 0, description: 'キャベツを千切りにして、トマトは一口大に切ります。', image_url: ''}, {index: 1, description: '豚ロースに薄力粉をまぶします。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/shogayaki/%E7%89%87%E6%A0%97%E7%B2%89%E3%82%92%E3%81%BE%E3%81%B5%E3%82%99%E3%81%99.jpeg'}, {index: 2, description: 'ボウルにたれの材料を入れて混ぜ合わせます。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/shogayaki/%E8%AA%BF%E5%91%B3%E6%96%99%E3%82%92%E6%B7%B7%E3%81%9B%E3%82%99%E5%90%88%E3%82%8F%E3%81%9B%E3%82%8B.jpeg'}, {index: 3, description: '中火で熱したフライパンにごま油をひき、2を入れて火が通り、両面にこんがりと焼き色が付くまで焼き、3を入れます。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/shogayaki/%E8%82%89%E3%82%92%E7%84%BC%E3%81%84%E3%81%A6%E8%AA%BF%E5%91%B3%E6%96%99%E3%82%92%E5%85%A5%E3%82%8C%E3%82%8B.jpeg'}, {index: 4, description: '中火で炒め合わせ、全体に味がなじんだら火から下ろします。', image_url: ''}, {index: 5, description: '1をのせたお皿に5を盛り付けて完成です。', image_url: ''}, ])

# ブロッコリーとツナのサラダ
tunaSalad = Recipe.create(title: 'ブロッコリーとツナのサラダ', comment: 'ツナとコーンとマヨネーズで、野菜嫌いな子どももモリモリ美味しく食べられます♪', amount: 2, calorie: 148, main_ingredient: 'ツナ缶', category: 'サラダ', tips: 'コーンは冷凍でなくても、何でもOKです。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/tunasalad/%E3%83%A1%E3%82%A4%E3%83%B3%E7%94%BB%E5%83%8F.jpeg', user_id: 1)
tunaSalad.ingredients.create([{index: 0, name: 'ブロッコリー', amount: '1株'}, {index: 1, name: '人参', amount: '1/4本'}, {index: 2, name: '冷凍コーン', amount: '好きなだけ'}, {index: 3, name: 'ごま', amount: '大匙2'}, {index: 4, name: 'ツナ', amount: '1缶'}, {index: 5, name: 'マヨネーズ', amount: '大さじ5~6'}, {index: 6, name: '麺つゆ', amount: '小さじ2'}, ])
tunaSalad.procedures.create([{index: 0, description: 'ブロッコリーは食べやすい大きさに、人参は千切りにし、一緒に2分くらい（好みの固さに合わせてお好みで）塩茹で。', image_url: 'https://smart-kitchen-dev.s3.ap-northeast-1.amazonaws.com/tunasalad/%E8%8C%B9%E3%81%A6%E3%82%99%E3%82%8B.jpeg'}, {index: 1, description: '冷凍コーンの場合はここで、茹でたブロッコリーの上にパラパラ乗せておきます。', image_url: ''} ])

# sample
# sample = Recipe.create(title: '', comment: '', amount: 1, calorie: 1, main_ingredient: '', category: '', tips: '', image_url: '', user_id: 1)
# sample.ingredients.create([{index: 0, name: '', amount: ''}, {index: 1, name: '', amount: ''}, {index: 2, name: '', amount: ''}, {index: 3, name: '', amount: ''}, {index: 4, name: '', amount: ''}, {index: 5, name: '', amount: ''}, {index: 6, name: '', amount: ''}, {index: 7, name: '', amount: ''}, {index: 8, name: '', amount: ''}, {index: 9, name: '', amount: ''}, {index: 10, name: '', amount: ''}, {index: 11, name: '', amount: ''}, {index: 12, name: '', amount: ''}, ])
# sample.procedures.create([{index: 0, description: '', image_url: ''}, {index: 1, description: '', image_url: ''}, {index: 2, description: '', image_url: ''}, {index: 3, description: '', image_url: ''}, {index: 4, description: '', image_url: ''}, {index: 5, description: '', image_url: ''}, {index: 6, description: '', image_url: ''}, {index: 7, description: '', image_url: ''}, {index: 8, description: '', image_url: ''}, {index: 9, description: '', image_url: ''}, {index: 10, description: '', image_url: ''}, {index: 11, description: '', image_url: ''}, {index: 12, description: '', image_url: ''}, ])
