version: '3'
services:
  api: # Ruby on Railsが起動するコンテナ
    build:
      context: .
      dockerfile: 'Dockerfile_dev'
    ports:
      - '3000:3000' # localhostの3000ポートでアクセスできるようにする
      - '80:80'
    volumes:
      - .:/smart-kitchen-api # アプリケーションファイルの同期
    depends_on:
      - db
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'" # entrypoint.shを作成したためコメントアウト
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # データの永続化
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  mysql_data: # データボリュームの登録
